Remotedata
Unai-Gomez-Diez/Superheroes pull request #1
Opened 2023-10-26 09:44 UTC by Unai-Gomez-Diez

## Description de la tarea

Obtener los datos de fichero json y mostrarlos

## ¿Cómo se ha implementado?

He utilizado retrofit para obtener los datos, he utilizado okhttps para comprobar los datos que hay en el json indicado

## Keywords

retrofit, model, map,

## Screenshots or Video
 Aqui muestra el print
![image](https://github.com/Unai-Gomez-Diez/Superheroes/assets/115726941/72ab9762-dbad-40af-a2c9-b5afb297728a)

Y aquí lo muestro con el debug para que se pueda ver mas claro que si se han obtenido los datos correctamente
![image](https://github.com/Unai-Gomez-Diez/Superheroes/assets/115726941/b769e991-ce90-42fc-b8a7-bb0ecce952c3)

2023-10-26 18:15 UTC, josem-perram requested changes
Hola Unai, te dejo comentarios generales a la PR.
En la descripción de la PR tienes que indicar qué se tienen que hacer. Algo como: recoger un listado de superheroes, biografía, etc. 

Además revisa los comentarios en el código que he realizado.

2023-10-26 18:15 UTC, jmperezra commented on app/src/main/java/com/ugdgomezdiez/superheroes/data/remote/ApiRemoteDataSource.kt
> +    private val apiClient: ApiClient= ApiClient()
Siempre es mejor pasar los objetos por constructor que crearlos dentro de la clase. Eso es así porque para hacer test de código necesitamos usar distintos tipos de ApiClient y si lo creas dentro, no tendré acceso desde fuera de la clase.

2023-10-26 18:15 UTC, jmperezra commented on app/src/main/java/com/ugdgomezdiez/superheroes/data/remote/ApiRemoteDataSource.kt
> +        val interceptor = HttpLoggingInterceptor()
Mmm otra vez esto aquí? no te has creado un ApiClient??

2023-10-26 18:15 UTC, jmperezra commented on app/src/main/java/com/ugdgomezdiez/superheroes/data/remote/ApiRemoteDataSource.kt
> +        }catch (e:Exception){
Intenta capturar cuando es TimeOutException y UnknownHostException para saber si tienes o no internet.

2023-10-26 18:15 UTC, jmperezra commented on app/src/main/java/com/ugdgomezdiez/superheroes/domain/Models.kt
> +import com.google.gson.annotations.SerializedName
Estos modelos deberían estar en la capa de datos, en la parte de remoto y no en el dominio. En el dominio ya tienes SuperHero. Además, deberían llamarse SuperHeroApiModel, si se hubiera puesto ese nombre quedaría más claro en qué carpeta va ubicado.

2023-10-26 20:47 UTC, Unai-Gomez-Diez commented
Lo había puesto antes pero al volver ha revisarlo me daba un error, ya si que esta solucionado y he comprobado que funcionara

2023-10-27 13:42 UTC, josem-perram approved these changes
Bien, te he dejado unos comentarios que deberás corregir en siguientes PRs.

2023-10-27 13:42 UTC, josem-perram commented on app/src/main/java/com/ugdgomezdiez/superheroes/data/remote/ApiRemoteDataSource.kt
> +
Ten cuidado con estos espacios, cual es la finalidad? para qué estan? Por favor, elimínalos en las próximas PRs

2023-10-27 16:11 UTC, merged